install: true
script:
- "./scripts/build.sh"
- "aws s3 sync ./public s3://jimmyandtheas.co.uk --region eu-west-2 --delete"
- "aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'"